# Generated by Django 5.2.8 on 2025-11-15 20:20

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_blogpost_certification_skill_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('job_title', models.CharField(max_length=200)),
                ('bio', models.TextField(help_text='Your professional bio/introduction')),
                ('short_bio', models.TextField(help_text='Brief bio for homepage/cards', max_length=300)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('location', models.CharField(max_length=100)),
                ('profile_image', models.ImageField(blank=True, upload_to='about/')),
                ('resume', models.FileField(blank=True, help_text='Upload your CV/Resume', upload_to='resumes/')),
                ('github_url', models.URLField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('twitter_url', models.URLField(blank=True)),
                ('portfolio_url', models.URLField(blank=True)),
                ('years_experience', models.IntegerField(default=0)),
                ('projects_completed', models.IntegerField(default=0)),
                ('happy_clients', models.IntegerField(blank=True, default=0, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'About',
            },
        ),
        migrations.CreateModel(
            name='PortfolioAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('page_views', models.IntegerField(default=0)),
                ('unique_visitors', models.IntegerField(default=0)),
                ('contact_form_submissions', models.IntegerField(default=0)),
                ('resume_downloads', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Portfolio Analytics',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Jonas Portfolio', max_length=100)),
                ('site_description', models.TextField(default='Full Stack Developer & AI Enthusiast')),
                ('maintenance_mode', models.BooleanField(default=False)),
                ('google_analytics_id', models.CharField(blank=True, max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Site Settings',
            },
        ),
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ['-published_date']},
        ),
        migrations.AlterModelOptions(
            name='certification',
            options={'ordering': ['-issue_date']},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['display_order', '-created_at']},
        ),
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ['category', '-proficiency', 'name']},
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='is_published',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Feature this post on the homepage'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='read_time',
            field=models.IntegerField(default=5, help_text='Estimated reading time in minutes'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='view_count',
            field=models.IntegerField(default=0, help_text='Number of times this post has been viewed'),
        ),
        migrations.AddField(
            model_name='certification',
            name='display_on_homepage',
            field=models.BooleanField(default=False, help_text='Show this certification on homepage'),
        ),
        migrations.AddField(
            model_name='certification',
            name='is_verified',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='project',
            name='display_order',
            field=models.IntegerField(default=0, help_text='Order in which projects are displayed'),
        ),
        migrations.AddField(
            model_name='project',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Show this project publicly'),
        ),
        migrations.AddField(
            model_name='project',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Feature this project on the homepage'),
        ),
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='skill',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Show this skill prominently'),
        ),
        migrations.AddField(
            model_name='skill',
            name='last_used',
            field=models.DateField(default=django.utils.timezone.now, help_text='When you last used this skill'),
        ),
        migrations.AddField(
            model_name='skill',
            name='years_experience',
            field=models.DecimalField(decimal_places=1, default=1.0, help_text='Years of experience with this skill', max_digits=3),
        ),
        migrations.AlterField(
            model_name='skill',
            name='category',
            field=models.CharField(choices=[('programming', 'Programming Languages'), ('framework', 'Frameworks & Libraries'), ('tool', 'Tools & Technologies'), ('soft', 'Soft Skills'), ('ai_ml', 'AI & Machine Learning'), ('cloud', 'Cloud & DevOps')], max_length=20),
        ),
        migrations.AlterField(
            model_name='skill',
            name='proficiency',
            field=models.IntegerField(help_text='Proficiency level from 1-100', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
